Controllers/ItemListingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using SilentAthleticsWebApp.Models;

using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Web;
using SilentAthleticsWebApp.Models.Images;

namespace SilentAthleticsWebApp.Controllers
{
    public class ItemListingController : Controller
    {
        private IItemRepository _itemRepository;
        private IWebHostEnvironment _env;
        private string _dir;

        public ItemListingController(IItemRepository repository, IWebHostEnvironment env)
        {
            _itemRepository = repository;
            _env = env;
            _dir = _env.WebRootPath;

        }



        public IActionResult Index()
        {
            IQueryable<ItemListing> allListings = _itemRepository.GetAllItemListings();
            return View(allListings);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ItemListing i)
        {

            _itemRepository.AddItemListing(i);


            return RedirectToAction("Details", new { id = i.ID });
        }
        [HttpPost]
        public IActionResult FileInModel(SomeForm someForm, ItemListing i)
        {
            Image image = new Image();
            



            using (var fileStream = new FileStream(Path.Combine(_dir, $"{someForm.Name}.png"), FileMode.Create, FileAccess.Write))
            {
               
                someForm.File.CopyTo(fileStream);
                image.ImagePath = fileStream.Name;
            }
            
            return RedirectToAction("Index");
        }

 //
 //
 //
        public IActionResult Details(int id)
        {
            //pulls from database and displays it in the view
            ItemListing item = _itemRepository.GetItemListingById(id);
            return View(item);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ItemListing itemListing = _itemRepository.GetItemListingById(id);

            return View(itemListing);
        }
        [HttpPost]
        public IActionResult Edit(ItemListing itemToUpdate, SomeForm someForm)
        {

            Image image = new Image();
            image.ImageTitle = someForm.Name;
            _itemRepository.UpdateItemListing(itemToUpdate);
            _itemRepository.Save();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete(ItemListing itemListing, int id)
        {
            return View();
        }


    }
}

Controllers/MeetupSchedulerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SilentAthleticsWebApp.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SilentAthleticsWebApp.Controllers
{
    public class MeetupSchedulerController : Controller
    {
        private IMeetupRepository _meetupRepository;  //_repository
        public int PageSize = 4;
        public MeetupSchedulerController(IMeetupRepository _meeting)  //Imeetuprepository**
        {
            _meetupRepository = _meeting;
        }



        public IActionResult Index()
        {
            IQueryable<MeetupScheduler>allMeetings=_meetupRepository.GetAllMeetings();
            return View(allMeetings);


        }

        [HttpGet]
        public IActionResult Create()
        {
            //returns create cshtml page
            return View();
        }

        [HttpPost]
        public IActionResult Create(MeetupScheduler m)
        {

            //save meet up being recieved to the database
            //returns the details page post addition of data

            MeetupScheduler meetup = new MeetupScheduler();




            _meetupRepository.AddMeetup(m);
            _meetupRepository.Save();

           
            return RedirectToAction("Details",  new { id = m.ID });  //anon class with one field "id"
        }

        public IActionResult Details(int id)
        {
            //pulls from database and displays it in view

            

            
            return View(_meetupRepository.GetMeetingById(id));

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            //grabs the obj from database to be edited

            MeetupScheduler meetup = _meetupRepository.GetMeetingById(id);
            return View(meetup);

        }

        [HttpPost]
        public IActionResult Edit(MeetupScheduler m)
        {

            _meetupRepository.Update(m);
            _meetupRepository.Save();
            
            return RedirectToAction("Details");
           
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            MeetupScheduler meetup = _meetupRepository.GetMeetingById(id);
            if (meetup != null)
            {
                return View(meetup);
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Delete(MeetupScheduler meetup, int id)
        {

            _meetupRepository.RemoveMeetup(id);
            _meetupRepository.Save();

            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />


    <style type="text/css">
        /* Set the size of the div element that contains the map */
        #map {
            height: 400px;
            /* The height is 400 pixels */
            width: 100%;
            /* The width is the width of the web page */
        }
    </style>

    <script>
        // Initialize and add the map
        function initMap() {
            map = new google.maps.Map(document.getElementById("map"), {
                center: { lat: 39.71394, lng: -104.98349 },
                zoom: 15,
            });
        }

    </script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Silent Athletics</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="MeetupScheduler" asp-action="Index">Meetup Scheduler</a>

                    </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
             




                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ItemListing" asp-action="Index">Create an Auction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                        </li>

                    

                </ul>
            </div>

            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">

            </form>
        </nav>
    </header>


    <div class="container" style="padding-top: 100px">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SilentAthleticsWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>



</body>
</html>